server.port=8080
application.recommendations-db.url=jdbc:h2:file:./transaction

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/credit_rules
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# TelegramBot
telegram.bot.token=8779339597:AAFodAa4E7x_OgzS4ChltWeMqih2kYx9g8Y
